### ISSUE TITLE
good done in MD editor,I hope add checkbox and table command,tks /NULL

### ISSUE THREAD

**Issue by wenbaofu** [mdickin/vscode-markdown-shortcuts#2]

**Comment by mdickin** [comment]
Thank you for the feedback! Checkboxes should be easy enough to do. I'll have to think through how to do tables intuitively.

**Comment by mdickin** [comment]
As of v0.4.0, Github Flavored Markdown (GFM) checkboxes are supported. You can also convert tabular (separated by tabs or 2+ spaces) data into a table.

**Comment by wenbaofu** [comment]
yes, you are right,table is also needed. and if there is a preview of the MD file. I only had installed Markdown Shortcuts and Markdown Checkbox in vscode 1.7.1 . I found the preview of the MD file can not work well(not sure the preview function in which extention)
the preview result like this:
MD file:
test 
test
preview:
test test

it seems lost one CRLF,when I add two CRLF，then preview can display one new line

**Comment by mdickin** [comment]
The Markdown preview is provided by Visual Studio Code, not either of those extensions.

What you're describing is expected behavior for Markdown. You can test it here as well: http://dillinger.io/

It's worth noting that the VSCode preview does not support checkboxes, as it doesn't recognize Github Flavored Markdown. The Markdown standard does not contain a checkbox
