### ISSUE TITLE
May Add <details> <summary> .. </summary> </details>

### ISSUE THREAD

**Issue by chinanf-boy** [mdickin/vscode-markdown-shortcuts#37]

**Comment by chinanf-boy** [comment]
```
<details> 

<summary> more info </summary> 
1.a

2.b
</details>
```
<details> 

<summary> more info </summary> 
1.a

2.b
</details>

**Comment by mdickin** [comment]
Interesting, I didn't know about this. Looks like this is part of the HTML5 specification rather than Markdown. It renders in Github (as long as you're not using IE or Edge) and the preview window in VS Code.

However, this seems like a better fit for using [Visual Studio Code snippets](https://code.visualstudio.com/docs/editor/userdefinedsnippets) rather than this extension.

**Comment by chinanf-boy** [comment]
i see , 

But i can't use `Visual Studio Code snippets` in markdown file 

how do ?❤️

when i create the `markdown.json`file, set the

``` json
	// like Example:
	"Print to console": {
		"prefix": "log",
		"body": [
			"console.log('$1');",
			"$2"
		],
		"description": "Log output to console"
	}
```

> in `md` file

snippets tips no show
