### ISSUE TITLE
project status still active?

### ISSUE THREAD

**Issue by zachvalenta** [mdickin/vscode-markdown-shortcuts#57]
Based on recent issues/PRs closed, the project looks inactive since February. 

Noticed because I checked up on a [previous issue I'd opened](https://github.com/mdickin/vscode-markdown-shortcuts/issues/49) (when had helpfully been implemented and closed very quickly) and realized the changes had never made it to master because there hasn't been a release in a while.

This extension has served me well and I appreciate the effort it takes to keep something like this going, so just want a status update to see where things stand (maybe something [along these lines](https://github.com/noirbizarre/flask-restplus/issues/612)).

**Comment by mdickin** [comment]
Hi Zach,

Yes, this project is still "active", though I admit I'm not very speedy with responses. Sorry about that!
I don't have any plans for future enhancements, though I am happy to review PRs from others

Are you referring to the ability to use double underscores for bold rather than double asterisks? That functionality was added in v0.11.0. 
![image](https://user-images.githubusercontent.com/16612667/68546577-648e0800-039d-11ea-9816-fb575280b075.png)

**Comment by zachvalenta** [comment]
Good stuff 👍🏼 

My bad, I checked the [releases page](https://github.com/mdickin/vscode-markdown-shortcuts/releases) and didn't see 0.11 there so didn't realize it was out; when I checked `~/.vscode/extensions/` I realized I had already been using it :)
